apiVersion: 1

datasources:
  - name: booptube-loki
    type: loki
    uid: booptube-loki
    access: proxy
    url: http://booptube-loki:3100
    isDefault: true
    editable: false
    jsonData:
      maxLines: 1000
